# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\FogSa\Desktop\code_\opener.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 246)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 20, 511, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_load_cfg = QtWidgets.QPushButton(self.frame)
        self.btn_load_cfg.setGeometry(QtCore.QRect(340, 20, 75, 23))
        self.btn_load_cfg.setObjectName("btn_load_cfg")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.label.setObjectName("label")
        self.radiobtn_localhost = QtWidgets.QRadioButton(self.frame)
        self.radiobtn_localhost.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.radiobtn_localhost.setChecked(True)
        self.radiobtn_localhost.setObjectName("radiobtn_localhost")
        self.btn_modify = QtWidgets.QPushButton(self.frame)
        self.btn_modify.setGeometry(QtCore.QRect(90, 170, 75, 23))
        self.btn_modify.setObjectName("btn_modify")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setGeometry(QtCore.QRect(90, 140, 75, 23))
        self.btn_add.setObjectName("btn_add")
        self.lineEdit_remote_ip = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_remote_ip.setGeometry(QtCore.QRect(180, 15, 141, 20))
        self.lineEdit_remote_ip.setWhatsThis("")
        self.lineEdit_remote_ip.setObjectName("lineEdit_remote_ip")
        self.radiobtn_remote = QtWidgets.QRadioButton(self.frame)
        self.radiobtn_remote.setGeometry(QtCore.QRect(110, 20, 89, 16))
        self.radiobtn_remote.setObjectName("radiobtn_remote")
        self.btn_del = QtWidgets.QPushButton(self.frame)
        self.btn_del.setGeometry(QtCore.QRect(170, 140, 75, 23))
        self.btn_del.setObjectName("btn_del")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_3.setObjectName("label_3")
        self.cbBox_folder_name = QtWidgets.QComboBox(self.frame)
        self.cbBox_folder_name.setGeometry(QtCore.QRect(90, 50, 69, 22))
        self.cbBox_folder_name.setObjectName("cbBox_folder_name")
        self.lineEdit_folder_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_folder_name.setGeometry(QtCore.QRect(90, 80, 371, 21))
        self.lineEdit_folder_name.setObjectName("lineEdit_folder_name")
        self.btn_open = QtWidgets.QPushButton(self.frame)
        self.btn_open.setGeometry(QtCore.QRect(170, 170, 75, 23))
        self.btn_open.setObjectName("btn_open")
        self.lineEdit_folder_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_folder_path.setGeometry(QtCore.QRect(90, 110, 371, 21))
        self.lineEdit_folder_path.setObjectName("lineEdit_folder_path")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_load_cfg.setText(_translate("Form", "Load Cfg"))
        self.label_2.setText(_translate("Form", "FolderPath: "))
        self.label.setText(_translate("Form", "FolderName: "))
        self.radiobtn_localhost.setText(_translate("Form", "localhost"))
        self.btn_modify.setText(_translate("Form", "Modify"))
        self.btn_add.setText(_translate("Form", "Add"))
        self.lineEdit_remote_ip.setToolTip(_translate("Form", "Remote IP Address"))
        self.lineEdit_remote_ip.setPlaceholderText(_translate("Form", "127.0.0.1"))
        self.radiobtn_remote.setText(_translate("Form", "remote"))
        self.btn_del.setText(_translate("Form", "Del"))
        self.label_3.setText(_translate("Form", "FolderName: "))
        self.btn_open.setText(_translate("Form", "Open"))
