# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\FogSa\Desktop\code_\opener.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 231)
        self.radiobtn_localhost = QtWidgets.QRadioButton(Form)
        self.radiobtn_localhost.setGeometry(QtCore.QRect(50, 40, 89, 16))
        self.radiobtn_localhost.setChecked(True)
        self.radiobtn_localhost.setObjectName("radiobtn_localhost")
        self.radiobtn_remote = QtWidgets.QRadioButton(Form)
        self.radiobtn_remote.setGeometry(QtCore.QRect(140, 40, 89, 16))
        self.radiobtn_remote.setObjectName("radiobtn_remote")
        self.cbBox_folder_name = QtWidgets.QComboBox(Form)
        self.cbBox_folder_name.setGeometry(QtCore.QRect(120, 70, 69, 22))
        self.cbBox_folder_name.setObjectName("cbBox_folder_name")
        self.lineEdit_folder_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_folder_name.setGeometry(QtCore.QRect(120, 100, 371, 21))
        self.lineEdit_folder_name.setObjectName("lineEdit_folder_name")
        self.btn_add = QtWidgets.QPushButton(Form)
        self.btn_add.setGeometry(QtCore.QRect(120, 160, 75, 23))
        self.btn_add.setObjectName("btn_add")
        self.lineEdit_remote_ip = QtWidgets.QLineEdit(Form)
        self.lineEdit_remote_ip.setGeometry(QtCore.QRect(210, 35, 113, 20))
        self.lineEdit_remote_ip.setObjectName("lineEdit_remote_ip")
        self.btn_modify = QtWidgets.QPushButton(Form)
        self.btn_modify.setGeometry(QtCore.QRect(120, 190, 75, 23))
        self.btn_modify.setObjectName("btn_modify")
        self.btn_del = QtWidgets.QPushButton(Form)
        self.btn_del.setGeometry(QtCore.QRect(200, 160, 75, 23))
        self.btn_del.setObjectName("btn_del")
        self.btn_open = QtWidgets.QPushButton(Form)
        self.btn_open.setGeometry(QtCore.QRect(200, 190, 75, 23))
        self.btn_open.setObjectName("btn_open")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 100, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_folder_path = QtWidgets.QLineEdit(Form)
        self.lineEdit_folder_path.setGeometry(QtCore.QRect(120, 130, 371, 21))
        self.lineEdit_folder_path.setObjectName("lineEdit_folder_path")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 71, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radiobtn_localhost.setText(_translate("Form", "localhost"))
        self.radiobtn_remote.setText(_translate("Form", "remote"))
        self.btn_add.setText(_translate("Form", "Add"))
        self.btn_modify.setText(_translate("Form", "Modify"))
        self.btn_del.setText(_translate("Form", "Del"))
        self.btn_open.setText(_translate("Form", "Open"))
        self.label.setText(_translate("Form", "FolderName: "))
        self.label_2.setText(_translate("Form", "FolderPath: "))
        self.label_3.setText(_translate("Form", "FolderName: "))
